[package]
name = "raze"
version = "0.1.0"
authors = ["Rodrigo Rivas Costa <rodrigorivascosta@gmail.com>"]
edition = "2018"

[lib]
crate-type=["cdylib"]

[[bin]]
name = "console"
path = "src/main.rs"

[[bin]]
name = "dump_op"
path = "src/dump_op.rs"
required-features = ["dump_ops"]

[profile.release]
lto = true
panic = "abort"
opt-level = 2

[dependencies]
zip = { version = "*", optional = true, default_features = false, features = ["deflate"] }
cfg-if = "*"
wasm-bindgen = "*"

[features]
default = ["zip"]
dump_ops = []
